services:
  identity-server:
    restart: always
    image: adityagole123/identity:latest
    command: python manage.py
    ports:
      - "8000:8000"
    volumes:
      - ./identity/:/app
      - identity_server_static_volume:/app/static
      - identity_server_media_volume:/app/media

  product-api:
    restart: always
    image: adityagole123/product_api:latest
    ports:
      - "8001:8001"
    volumes:
      - ./product_api/:/app
      - products_api_static_volume:/app/static
      - products_api_media_volume:/app/media
    depends_on:
      - "identity-server"

  web-client:
    image: adityagole123/next-client:latest
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    restart: always
    command: yarn dev
    ports:
      - "3001:3001"
    volumes: 
      - ./nuxt-client/:/app
      - web_client_node_modules:/app/node_modules/
    depends_on:
      - "identity-server"
      - "product-api"

volumes:
  identity_server_static_volume:
  identity_server_media_volume:
  products_api_static_volume:
  products_api_media_volume:
  web_client_node_modules:


